CREATE TABLE IF NOT EXISTS student (
  reg_no CHAR(10) NOT NULL ,
  name VARCHAR(30) NOT NULL,
  sem INT NOT NULL,
  dept VARCHAR(30) NOT NULL,
  pswd VARCHAR(20) NOT NULL,
  paystatus TINYINT NOT NULL,
  PRIMARY KEY (reg_no,pswd)
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS staff (
  staff_id CHAR(10) NOT NULL,
  pswd VARCHAR(20) NOT NULL ,
  cat VARCHAR(15) NOT NULL,
  name VARCHAR(30) NOT NULL,
  dept VARCHAR (30),
  amt INT ,
  paystatus TINYINT NOT NULL,
  PRIMARY KEY (staff_id,pswd)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS amount (
  reg_no CHAR(10) NOT NULL,
  lib_fine INT,
  fee INT ,
  PRIMARY KEY (reg_no)
)ENGINE=INNODB;
